### ISSUE TITLE
Implement subtitle delaying

### ISSUE THREAD

**Issue by jGRite** [mpc-qt/mpc-qt#94] opened 2023-09-15 23:47 UTC
First, I want to let everyone that is working on this know that this is a great media player, and it is so close to being an equal replacement for MPC-HC. There are a few things either missing, or I can't find easily that would make it good enough to use daily. Sadly, I'm just a user so I don't know enough to help.
There seems to be no way to do subtitle delaying. I'm not sure what 'Increment' and 'Decrement' does. Maybe that speeds up the video playback? I'm unsure if there's a way to go to the next file in the list without going through the current video's chapters. Finally, there's no larger skip forward and backward only regular and finely. Hopefully some of this will come to this nice program.

**Comment by cmdrkotori** [comment] 2023-09-23 12:46
>There seems to be no way to do subtitle delaying.

In my 15 years of using mpc-hc and clones, I have never once used this feature.  Just like PnS.   One could say get better rips but I'll implement this if it's straightforward.

>Finally, there's no larger skip forward and backward only regular and finely.

Back in the day mpc-hc did not have this, that's why it's missing.  This should be fairly simple to add if my memory of the codebase serves me right.

**Comment by cmdrkotori** [comment] 2024-04-29 01:18
Renaming issue.

Your other feature request is a duplicate of #117.

**Closed** 2024-09-13 10:02 UTC
Labels: feature request
