### ISSUE TITLE
GPU/CPU usage vastly different to mpv

### ISSUE THREAD

**Issue by Nyunyun** [mpc-qt/mpc-qt#142] opened 2024-08-22 13:07 UTC
Heya,
I noticed that on mpv with an 8K video my CPU usage is considerably lower than on mpc-qt.

![2024-08-22_14-45](https://github.com/user-attachments/assets/185d0cc7-e398-45e8-a433-43aa11d7198c)

[The video in question is this one](https://www.youtube.com/watch?v=5USuekk16e0) (downloaded it)

I set mpc-qt to use hw decoding on all file types and the backend to auto.
There also doesn't seem to be a difference, no matter which backend I set.

My mpv uses these:
`profile=gpu-hq`
`gpu-api=vulkan`
`vulkan-async-compute=yes`
`vulkan-async-transfer=yes`
`vulkan-queue-count=1`
`hwdec=auto-copy`

With this I get `nvdec-copy` in mpv, while on mpc-qt (with ctrl+j) I can't see the hw decoder.
The upside I found with this is, that the power usage is lower with mpc-qt by about 40W (for the whole system).
This seems to be due to mpv forcing a higher frequency and thus 4@16, while mpc-qt leaves the GPU at 2@16.

My system is as follows:
Arch, completely up to date
NVIDA RTX 4090 with latest proprietary drivers 555.58.02-01
AMD Ryzen 7800X3D
KDE Plasma 6 on X11

I "installed" mpc-qt as AppImage with GearLever

If there's anything else I can provide then let me know

**Comment by cmdrkotori** [comment] 2024-11-18 13:03
That's because up until b490d9e4b1a66a318a708eb290a3b00dd1d4776e nvdec wasn't an option.  This should be fixed in the next release.

**Comment by tbertels** [comment] 2024-11-19 22:05
Let's close this then.
Feel free to open a new issue mentioning this one if the problem is still there with a recent build from master or [release/24.12](https://github.com/mpc-qt/mpc-qt/tree/release/24.12).
You can download a recent build from https://github.com/mpc-qt/mpc-qt/actions (for instance on https://github.com/mpc-qt/mpc-qt/actions/runs/11903422212) if you don't want to use the AUR.

**Closed by tbertels** 2024-11-19 22:05 UTC
